import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles((theme) => ({
  loginPage: {
    height: "100vh",
    width: "100vw",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(160deg, #0f172a 0%, #1e293b 50%, #1a2540 100%)",
    position: "relative",
    overflow: "hidden",
    "&::before": {
      content: '""',
      position: "absolute",
      top: "-20%",
      right: "-10%",
      width: "500px",
      height: "500px",
      borderRadius: "50%",
      background: "radial-gradient(circle, rgba(180,30,30,0.08) 0%, transparent 70%)",
      pointerEvents: "none",
    },
    "&::after": {
      content: '""',
      position: "absolute",
      bottom: "-20%",
      left: "-5%",
      width: "400px",
      height: "400px",
      borderRadius: "50%",
      background: "radial-gradient(circle, rgba(30,41,59,0.3) 0%, transparent 70%)",
      pointerEvents: "none",
    },
  },
  loginContainer: {
    width: "400px",
    maxWidth: "92vw",
    background: "#ffffff",
    boxShadow: "0 25px 50px -12px rgba(0,0,0,0.3)",
    borderRadius: "16px",
    padding: "40px 36px 36px",
    position: "relative",
    zIndex: 1,
    animation: "$fadeInUp 0.45s ease-out",
  },
  "@keyframes fadeInUp": {
    from: {
      opacity: 0,
      transform: "translateY(16px)",
    },
    to: {
      opacity: 1,
      transform: "translateY(0)",
    },
  },
  logoWrapper: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "6px",
  },
  logo: {
    height: "64px",
    width: "auto",
    objectFit: "contain",
  },
  subtitle: {
    textAlign: "center",
    fontSize: "14px !important",
    color: "#64748b",
    marginBottom: "28px !important",
    fontFamily: "Inter, sans-serif !important",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "0px",
  },
  inputWrapper: {
    marginBottom: "16px",
  },
  inputLabel: {
    fontSize: "13px !important",
    fontWeight: "600 !important",
    color: "#374151",
    marginBottom: "6px !important",
    display: "block",
    fontFamily: "Inter, sans-serif !important",
  },
  input: {
    border: "1.5px solid #e2e8f0",
    borderRadius: "10px",
    width: "100%",
    height: "44px",
    backgroundColor: "#f8fafc",
    transition: "border-color 200ms ease, box-shadow 200ms ease, background-color 200ms ease",
    "&:hover": {
      borderColor: "#94a3b8",
    },
    "&:focus-within": {
      borderColor: "#1e293b",
      boxShadow: "0 0 0 3px rgba(30,41,59,0.08)",
      backgroundColor: "#fff",
    },
    "& .MuiInputBase-input": {
      color: "#1e293b",
      fontSize: "14px",
      padding: "0 12px",
      height: "44px",
      fontFamily: "Inter, sans-serif",
      "&::placeholder": {
        color: "#94a3b8",
        opacity: 1,
      },
    },
  },
  inputIcon: {
    color: "#94a3b8",
    fontSize: "20px !important",
    marginRight: "4px",
    marginLeft: "8px",
  },
  visibilityIcon: {
    color: "#94a3b8",
    fontSize: "20px !important",
  },
  loginButton: {
    marginTop: "8px !important",
    color: "#fff !important",
    background: "#1e293b !important",
    borderRadius: "10px !important",
    height: "44px",
    fontWeight: "600 !important",
    fontSize: "15px !important",
    fontFamily: "Inter, sans-serif !important",
    textTransform: "none !important",
    boxShadow: "0 2px 8px rgba(30,41,59,0.25) !important",
    transition: "all 200ms ease !important",
    "&:hover": {
      background: "#0f172a !important",
      boxShadow: "0 4px 16px rgba(30,41,59,0.35) !important",
    },
  },
}));
