import React from "react";

import { makeStyles } from "@mui/styles";
export const useStyles = makeStyles((theme) => ({
  loginContainer: {
    height: "auto",
    width: "400px",
    maxWidth: "95vw",
    background: "#ffffff",
    boxShadow: "0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.06)",
    borderRadius: "16px",
    opacity: 1,
    padding: "48px 40px",
  },
  loginPage: {
    height: "100vh",
    width: "100vw",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #f0fdfa 0%, #e0f2fe 50%, #f0fdfa 100%)",
  },
  header: {
    textAlign: "center",
    fontSize: "2.226rem",
    font: "Inter",
    letterSpacing: 0,
    color: "#0d9488",
    opacity: 1,
  },
  welcome: {
    textAlign: "center",
    font: "normal normal 600 24px/34px Inter",
    letterSpacing: 0,
    color: "#1e293b",
    opacity: 1,
  },
  inputContainer: {
    padding: "0px",
    margin: "0px",
    paddingTop: "16px",
  },
  forgetpass: {
    textAlign: "right",
    textDecoration: "underline",
    fontSize: "0.875rem",
    font: "Inter",
    letterSpacing: 0,
    color: "#0d9488",
    cursor: "pointer",
    opacity: 1,
    "&:hover": {
      color: "#0f766e",
    },
  },
  loginPostRequest: {
    color: "#ffffff",
    background: "linear-gradient(135deg, #0d9488 0%, #14b8a6 100%)",
    borderRadius: "10px",
    width: "100%",
    maxWidth: "320px",
    fontWeight: "600",
    height: "44px",
    fontSize: "1rem",
    "&:hover": {
      background: "linear-gradient(135deg, #0f766e 0%, #0d9488 100%)",
      boxShadow: "0 4px 12px rgba(13, 148, 136, 0.4)",
      transform: "translateY(-1px)",
    },
    transition: "all 250ms cubic-bezier(0.4, 0, 0.2, 1)",
  },
  input: {
    border: "1.5px solid #e2e8f0",
    borderRadius: "10px",
    opacity: 1,
    maxWidth: "320px",
    width: "320px",
    height: "44px",
    maxHeight: "44px",
    marginBottom: "16px",
    backgroundColor: "#f8fafc",
    transition: "border-color 250ms cubic-bezier(0.4, 0, 0.2, 1), box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1)",
    "&:hover": {
      borderColor: "#0d9488",
    },
    "&:focus-within": {
      borderColor: "#0d9488",
      boxShadow: "0 0 0 3px rgba(13, 148, 136, 0.1)",
      backgroundColor: "#ffffff",
    },
    "& .MuiInputBase-input": {
      color: "#1e293b",
      fontSize: "15px",
      marginRight: "10px",
      "&::placeholder": {
        color: "#94a3b8",
        opacity: 1,
      },
    },
  },
}));
